[versions]
agp = "8.10.1"
android-compileSdk = "35"
android-minSdk = "24"
android-targetSdk = "35"
androidx-activity = "1.10.1"
androidx-appcompat = "1.7.1"
androidx-constraintlayout = "2.2.1"
androidx-core = "1.16.0"
androidx-espresso = "3.6.1"
androidx-lifecycle = "2.9.0"
androidx-testExt = "1.2.1"
composeMultiplatform = "1.8.1"
coreSplashscreen = "1.0.1"
either = "1.2.1"
junit = "4.13.2"
kermit = "2.0.6"
kermitVersion = "2.0.5"
kotlin = "2.2.0"
kotzillaSdk = "1.1.0"
kvault = "1.12.0"
lifecycleViewmodelCompose = "2.9.1"
material3WindowSizeClassAndroid = "1.3.2"
koin = "4.1.0"
navigationCompose = "2.8.0-alpha13"
window = "1.4.0"
windowCore = "1.4.0"
kotlinxSerializationJson = "1.8.1"
ktorVersion = "3.1.3"
logbackClassicVersion = "1.5.18"
statelyCommon = "2.0.6"
gmazzo-buildconfig-version = "5.6.6"
kotlinx-datetime = "0.6.2"
room = "2.7.2"
ksp = "2.2.0-2.0.2"
sqlite = "2.5.2"
kotzilla = "1.1.0"

[libraries]
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-window-core = { module = "androidx.window:window-core", version.ref = "windowCore" }
androidx-window = { module = "androidx.window:window", version.ref = "window" }
either = { module = "net.orandja.kt:either", version.ref = "either" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
kermit-v205 = { module = "co.touchlab:kermit", version.ref = "kermitVersion" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-testExt-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-testExt" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-material3-window-size-class1-android = { group = "androidx.compose.material3", name = "material3-window-size-class-android", version.ref = "material3WindowSizeClassAndroid" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }

kotzilla-sdk = { module = "io.kotzilla:kotzilla-sdk", version.ref = "kotzillaSdk" }
kvault = { module = "com.liftric:kvault", version.ref = "kvault" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }

# ktor client
ktorClientCore = { module = "io.ktor:ktor-client-core", version.ref = "ktorVersion" }
ktorClientAndroid = { module = "io.ktor:ktor-client-android", version.ref = "ktorVersion" }
ktorClientCio = { module = "io.ktor:ktor-client-cio", version.ref = "ktorVersion" }
ktorClientSerialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktorVersion" }
ktorClientLogging = { module = "io.ktor:ktor-client-logging", version.ref = "ktorVersion" }
ktorClientContentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorVersion" }
ktorClientAuth = { module = "io.ktor:ktor-client-auth", version.ref = "ktorVersion" }
logbackClassic = { module = "ch.qos.logback:logback-classic", version.ref = "logbackClassicVersion" }
ktorSerializationJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktorVersion" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktorVersion" }

# Room
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
gmazzo-buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "gmazzo-buildconfig-version" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "room" }
# kotzilla = { id = "io.kotzilla:kotzilla-plugin", version.ref = "kotzilla" }
